# Generated by Django 3.2.4 on 2021-10-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catnm', models.CharField(max_length=100, unique=True)),
                ('caticonnm', models.CharField(max_length=50)),
            ],
        ),
    ]
