# Generated by Django 3.2.4 on 2021-10-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20211028_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcatid', models.AutoField(primary_key=True, serialize=False)),
                ('catnm', models.CharField(max_length=50)),
                ('subcatnm', models.CharField(max_length=50, unique=True)),
                ('caticonnm', models.CharField(max_length=100)),
            ],
        ),
    ]
